LEDGER = "C:\\Users\\Kris\\Currawong Resources Pty Ltd\\Currawong Resources Pty Ltd - " \
         "DataShed Export\\00_Audit\\XRF\\CRWSYSXRFLedger.csv"

XRF_PROCESSED = "C:\\Users\\Kris\\Currawong Resources Pty Ltd\\Currawong Resources Pty Ltd - DataShed Data Bridging\\pXRF"

XRF_RAW_FOLDER = "C:\\Users\\Kris\\OneDrive - Kristoffer Montefalcon\\Documents\\Dev\\Currawong\\XRF\\XRF_RAW_COPY"

LEDGER_XRF_LOADED_COLUMN = "Orig_Filename"

LEDGER_FORMAT = [
    'Batch_No',
    'Instrument_SN',
    'Analyzed_Date',
    'Analysis_Count',
    'DataSet',
    'Sample_Type',
    'Analyzed_By',
    'First_SampleID',
    'Last_SampleID',
    'Orig_Filename',
]

MONTHLY_FOLDER = "C://Users//Kris//Currawong Resources Pty Ltd//Currawong Resources Pty Ltd - 2023-04 April 2023"

MONTH = 4

XRF_EXPORT_FORMAT = [
    'Instrument_SN',
    'Reading',
    'ActionDate',
    'ActionTime',
    'Mode',
    'User_Factor_Name',
    'Field4',
    'Collimated',
    'Latitude_In_Degrees',
    'Longitude_In_Degrees',
    'UnitCode',
    'Mg',
    'Mg_Error',
    'Al',
    'Al_Error',
    'Si',
    'Si_Error',
    'P',
    'P_Error',
    'S',
    'S_Error',
    'K',
    'K_Error',
    'Ca',
    'Ca_Error',
    'Ti',
    'Ti_Error',
    'V',
    'V_Error',
    'Cr',
    'Cr_Error',
    'Mn',
    'Mn_Error',
    'Fe',
    'Fe_Error',
    'Co',
    'Co_Error',
    'Ni',
    'Ni_Error',
    'Cu',
    'Cu_Error',
    'Zn',
    'Zn_Error',
    'As',
    'As_Error',
    'Se',
    'Se_Error',
    'Rb',
    'Rb_Error',
    'Sr',
    'Sr_Error',
    'Y',
    'Y_Error',
    'Zr',
    'Zr_Error',
    'Nb',
    'Nb_Error',
    'Mo',
    'Mo_Error',
    'Ag',
    'Ag_Error',
    'Cd',
    'Cd_Error',
    'Sn',
    'Sn_Error',
    'Sb',
    'Sb_Error',
    'Ba',
    'Ba_Error',
    'La',
    'La_Error',
    'Ce',
    'Ce_Error',
    'Pr',
    'Pr_Error',
    'Nd',
    'Nd_Error',
    'W',
    'W_Error',
    'Au',
    'Au_Error',
    'Hg',
    'Hg_Error',
    'Pb',
    'Pb_Error',
    'Bi',
    'Bi_Error',
    'Th',
    'Th_Error',
    'U',
    'U_Error',
    'LE',
    'LE_Error',
    'Note',
    'Field1',
    'Field3',
    'SampleID',
    'Field2',
    'Live_Time1',
    'Live_Time2',
    'Live_Time3',
    'Field_Label1',
    'Field_Label2',
    'Field_Label3',
    'Field_Label4',
    'Field_Label5',
    'Field5',
    'Field_Label6',
    'Field6',
    'Field_Label7',
    'Field7',
]

XRF_RAW_COL_RENAME = {
    'Instrument Serial Num': 'Instrument_SN',
    'Reading #': 'Reading',
    'Date': 'ActionDate',
    'Time': 'ActionTime',
    'Method Name': 'Mode',
    'User Factor Name': 'User_Factor_Name',
    'Test Label': 'Field4',
    'Collimation Status':'Collimated',
    'Latitude': 'Latitude_In_Degrees',
    'Longitude': 'Longitude_In_Degrees',
    'Units': 'UnitCode',
    'Notes': 'Note',
    'Operator': 'Field1',
    'Project No.': 'Field3',
    'Sample ID': 'SampleID',
    'Sample Type': 'Field2',
    'Real Time 1': 'Live_Time1',
    'Real Time 2': 'Live_Time2',
    'Real Time 3': 'Live_Time3',
}
